---
name: Norminette

on:
  push:

jobs:
  check-norminette:
    name: Norminette
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Norminette
        uses: 42School/norminette
        with:
          args: '-RCheckForbiddenSourceHeader'
