---
name: Norminette

on:
  push:

jobs:
  check-norminette:
    name: Norminette
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install norminette
        run: |
          pip install norminette
        
      - name: Run norminette
        run: |
          echo "Running norminette to check coding standards..."
          norminette $(find . -name "*.c" -o -name "*.h" | grep -v test) || echo "Norminette found style issues - see output above"

     # - name: Norminette
     #   uses: 42School/norminette
     #   with:
     #     args: '-RCheckForbiddenSourceHeader'
